// SET GENERAL ACCOUNT INFO
export const SET_GENERAL_ACCOUNT_INFO = 'SET_GENERAL_ACCOUNT_INFO';

// SET DISPLAY
export const SET_COLOR_MODE = 'SET_COLOR_MODE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const ADD_SEARCH_FILTER = 'ADD_SEARCH_FILTER';
export const REMOVE_SEARCH_FILTER = 'REMOVE_SEARCH_FILTER';

// STAR SCREEN
export const SET_STAR_SCREEN = 'SET_STAR_SCREEN';
export const REMOVE_STAR = 'REMOVE_STAR';

// SET MAP
export const SET_REGION = 'SET_REGION';