// SET GENERAL ACCOUNT INFO
export const SET_GENERAL_ACCOUNT_INFO = 'SET_GENERAL_ACCOUNT_INFO';

// SET DISPLAY
export const SET_COLOR_MODE = 'SET_COLOR_MODE';

// SET FILTER
export const ADD_SEARCH_FILTER = 'ADD_SEARCH_FILTER';
export const REMOVE_SEARCH_FILTER = 'REMOVE_SEARCH_FILTER';

// SET LANGUAGE
export const SET_LANGUAGE = 'SET_LANGUAGE';